import appium
import playwright
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
from appium.webdriver.common.touch_action import TouchAction
from selenium import webdriver as webdriver_chrome
from selenium.webdriver import ActionChains
from selenium.webdriver.common.actions import interaction
from selenium.webdriver.common.actions.action_builder import ActionBuilder
from selenium.webdriver.common.actions.pointer_input import PointerInput
from selenium.webdriver.common.by import By
from appium.webdriver.common.mobileby import MobileBy
import time
import pyautogui
from selenium.webdriver.support.wait import WebDriverWait
from datetime import datetime
# from selenium.webdriver.common.devtools.v121 import page

desired_capabilities = {
  "platformName": "iOS",
  "appium:deviceName": "iPhone 12",
  "appium:platformVersion": "17.5.1",
  "appium:automationName": "XCUITest",
  "appium:udid": "00008101-001E00D22182001E",
  "appium:app": "/Users/nityaprakashpanigrahi/Downloads/MyMedela.ipa",
  "appium:bundleId": "com.medela.mymedela.q",
  "appium:xcodeOrgId": "JH7VLN8YGT",
  "appium:xcodeSigningId": "iPhone Developer",
  "appium:noReset": True,
  "appium:xcodeVersion": "15.4",
  "allowInvisibleElements":True,
  "newCommandTimeout": 120  # Set the command timeout to 120 seconds
}

mobile_driver = webdriver.Remote(command_executor="http://127.0.0.1:4723",desired_capabilities=desired_capabilities)
# time.sleep(2)
# mobile_driver.switch_to.alert.accept()
# time.sleep(2)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(200, 495)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
mobile_driver.implicitly_wait(10)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="CONTINUE"])[2]').click()
# time.sleep(2)
# mobile_driver.switch_to.alert.accept()
# # mobile_driver.find_element(By.XPATH,'//XCUIElementTypeButton[@name="LOG-IN"]').click()
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeStaticText[@name=\"DON\'T HAVE AN ACCOUNT? SIGN-UP"]').click()
# time.sleep(3)
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeTextField[@name="Email **"]').click()
Email='iosautomation19@yopmail.com'
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value='Email **').send_keys(Email)
# time.sleep(2)
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Send verification code").click()
# chrome_driver = webdriver_chrome.Chrome()
# # Use Chrome driver to access the web page and extract data
# # Replace with your specific actions and data extraction logic
# chrome_driver.maximize_window()
# chrome_driver.get("https://yopmail.com")
# time.sleep(8)
# chrome_driver.find_element(By.XPATH,"//input[@id='login']").send_keys(Email)
# chrome_driver.find_element(By.XPATH,"//i[contains(text(),'')]").click()
# chrome_driver.switch_to.frame(chrome_driver.find_element(By.XPATH,"//iframe[@id='ifmail']"))
# time.sleep(5)
# Code=chrome_driver.find_element(By.XPATH,"//span[contains(text(),'Your code is')]").text
# print(Code)
# Verification_Code=Code[-6:]
# Verification_code=str(Verification_Code)
# print(Verification_Code)
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeTextField[@name="Verification Code*"]').click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Verification Code*").send_keys(Verification_code)
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Verify code").click()
# time.sleep(3)
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeSecureTextField[@name="Password **"]').click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Password **").send_keys("Medela2024")
# mobile_driver.find_element(By.XPATH,"//XCUIElementTypeSecureTextField[@name='Confirm New Password*']").click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Confirm New Password*").send_keys("Medela2024")
# time.sleep(2)
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeButton[@name="Sign up"]').click()
# time.sleep(5)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Your Name / Nickname *"])[3]').send_keys("Mom")
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Baby Birth/Due Date *"])[3]').click()
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="1"])[2]').click()
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="OK"]').click()
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="Horizontal scroll bar, 1 page"]').send_keys('Baby1')
# # mobile_driver.find_element(by=AppiumBy,value="Horizontal scroll bar, 1 page").send_keys("Baby1")
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeButton[@name="Done"]').click()
# time.sleep(2)
# mobile_driver.swipe(180,590,180,280,300)
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="Girl"]').click()
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="NEXT"]').click()
# time.sleep(2)
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="I DON'T HAVE A MEDELA PUMP").click()
# print("*User Successfully Registered*")
# time.sleep(10)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# # Cross icon to close tools screen
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="CloseTracking"]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]').click()
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# # Diaper
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Diaper").click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Both_icon").click()
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(361, 489)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
# print("*Diaper Tracking Successful*")
# time.sleep(3)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# #Bottle
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Bottle").click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="mix milk selector").click()
# mobile_driver.swipe(340,450,120,450,300)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(361, 489)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
# print("*Bottle Tracking Successful*")
# time.sleep(3)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# # Sleep
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Sleep").click()
# time.sleep(1)
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="START").click()
# time.sleep(5)
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="PAUSE").click()
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(361, 489)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
# print("*Sleep Tracking Successful*")
# time.sleep(3)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# # Length
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Length").click()
# mobile_driver.swipe(320,350,100,350,300)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(361, 489)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
# print("*Length Tracking Successful*")
# time.sleep(3)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# # Weight
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Weight").click()
# mobile_driver.swipe(320,280,150,280,300)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(361, 489)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
# print("*Weight Tracking Successful*")
# time.sleep(3)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# # Breastfeeding
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Breastfeeding").click()
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Both"])[3]').click()
# time.sleep(5)
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="Left Timer"]').click()
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(361, 489)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
# print("*Breastfeeding Tracking Successful*")
# time.sleep(3)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(345, 700)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# # Pumping
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Pumping").click()
# time.sleep(1)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="START"])[2]').click()
# time.sleep(5)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="PAUSE"])[2]').click()
# mobile_driver.swipe(315,630,200,630,300)
# mobile_driver.swipe(60,450,60,250,300)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(361, 489)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
# print("*Manual Pumping Successful*")
# mobile_driver.implicitly_wait(10)
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="MORE").click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="My Profile Change name, log-out, etc").click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="LOG OUT").click()
# time.sleep(2)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(194, 423)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# print("*User successfully Logged out*")
# time.sleep(5)
mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="CONTINUE"])[2]').click()
time.sleep(2)
mobile_driver.switch_to.alert.accept()
print(mobile_driver.get_window_rect())
mobile_driver.find_element(By.XPATH,'//XCUIElementTypeTextField[@name="Email *"]').send_keys(Email)
mobile_driver.find_element(By.XPATH,'//XCUIElementTypeSecureTextField[@name="Password *"]').send_keys("Medela2024")
mobile_driver.find_element(By.XPATH,'//XCUIElementTypeButton[@name="LOG-IN"]').click()
print("*User successfully Logged in*")
time.sleep(5)
mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Connect Pump"])[2]').click()
mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Pump in Style Hands-free").click()
mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="CONTINUE"])[2]').click()
time.sleep(5)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Cleaning"])[2]').click()
# time.sleep(10)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Cleaning"])[2]').click()
time.sleep(5)
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="Cleaning"]/XCUIElementTypeOther').click()
# mobile_driver.swipe(330,420,175,420,300)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="How to Sanitize"])[2]').click()
# time.sleep(10)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="How to Sanitize"])[2]').click()
# time.sleep(30)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="How to Sanitize"])[2]/XCUIElementTypeOther').click()
mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="Pump now").click()
mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="START"])[2]').click()
a1=mobile_driver.get_device_time()
a1=a1[11:19]
a1 = datetime.strptime(a1, "%H:%M:%S")
# print(a1[11:19])
time.sleep(60)
mobile_driver.background_app(10)
time.sleep(2)
mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="PAUSE"])[2]').click()
a2=mobile_driver.get_device_time()
a2=a2[11:19]
a2 = datetime.strptime(a2, "%H:%M:%S")
# print(a2[11:19])
diff=a2-a1
print(diff)

# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="START"])[2]').click()
# timer_duration=timer_duration[3:]
# timer_duration=timer_duration.replace(":","")
# print(timer_duration)
mobile_driver.swipe(315,630,200,630,300)
mobile_driver.swipe(60,450,60,250,300)
mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="Add Note"])[3]').send_keys("This is a Test")
actions = ActionChains(mobile_driver)
actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(361, 489)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()
mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="SAVE").click()
time.sleep(3)
mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="CloseTracking"]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]').click()
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(200, 495)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# mobile_driver.switch_to.alert.accept()
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeOther[@name="STATS"]').click()
time.sleep(2)
actions = ActionChains(mobile_driver)
actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(90, 440)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()
# mobile_driver.implicitly_wait(10)
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="MORE").click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="My Profile Change name, log-out, etc").click()
# mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="LOG OUT").click()
# time.sleep(2)
# actions = ActionChains(mobile_driver)
# actions.w3c_actions = ActionBuilder(mobile_driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(194, 423)
# actions.w3c_actions.pointer_action.pointer_down()
# actions.w3c_actions.pointer_action.pause(0.1)
# actions.w3c_actions.pointer_action.release()
# actions.perform()
# time.sleep(5)
# mobile_driver.find_element(By.XPATH,'(//XCUIElementTypeOther[@name="CONTINUE"])[2]').click()
# time.sleep(2)
# mobile_driver.switch_to.alert.accept()
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeTextField[@name="Email *"]').send_keys("iosautomation44@yopmail.com")
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeSecureTextField[@name="Password *"]').send_keys("Medela2024")
# mobile_driver.find_element(By.XPATH,'//XCUIElementTypeButton[@name="LOG-IN"]').click()
# time.sleep(2)
# Error=mobile_driver.find_element(by=AppiumBy.ACCESSIBILITY_ID,value="We can't seem to find your account.").text
# print("Unable to Login as "+Error)